name: Update Docker Container

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    environment: XScraper

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get self ip
        id: self_ip
        run: |
          SELF_IP=$(curl -s https://api.ipify.org)
          echo "$SELF_IP"
          echo "self_ip=$SELF_IP" >> $GITHUB_OUTPUT

      - name: Get droplet information
        id: droplet_ip
        run: |
          DROPLET_IP=$(doctl compute droplet get xscraper-01 --format PublicIPv4 --no-header)
          DROPLET_ID=$(doctl compute droplet get xscraper-01 --format ID --no-header)
          echo "droplet_ip=$DROPLET_IP" >> $GITHUB_OUTPUT
          echo "droplet_id=$DROPLET_ID" >> $GITHUB_OUTPUT

      - name: Wait for MINUTE % 10 == 6
        run: |
          while true; do
            MINUTE=$(date +%M)
            if [ $((MINUTE % 10)) -eq 2 ]; then
              break
            fi
            sleep 10
          done

      - name: Add self IP to droplet firewall
        id: add_self_ip
        run: |
          doctl compute firewall add-rules \
            ${{ steps.droplet_ip.outputs.droplet_id }} \
            --inbound-rules="protocol:tcp,ports:22,address:$SELF_IP" \
            --outbound-rules="protocol:tcp,ports:22,address:$SELF_IP"

      - name: Wait for MINUTE % 10 == 3
        run: |
          while true; do
            MINUTE=$(date +%M)
            if [ $((MINUTE % 10)) -eq 2 ]; then
              break
            fi
            sleep 10
          done

      - name: SSH into droplet
        id: ssh
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{ steps.droplet_ip.outputs.droplet_ip }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY_ED }}
          script: bash update_container.sh

      - name: Remove self IP from droplet firewall
        if: ${{ steps.add_self_ip.outputs.outcome == 'success' }}
        run: |
          doctl compute firewall remove-rules \
            ${{ steps.droplet_ip.outputs.droplet_id }} \
            --inbound-rules="protocol:tcp,ports:22,address:$SELF_IP" \
            --outbound-rules="protocol:tcp,ports:22,address:$SELF_IP"
